/**
 * Static manifest of all safety icons in public/SafetyIcons/.
 * Category derived from filename prefix at build time.
 * Generated from the flat public/SafetyIcons/ folder.
 */

import { getCategoryFromFilename, type SafetyIconCategory } from './safetyIcons';

export interface SafetyIconEntry {
  filename: string;
  category: SafetyIconCategory;
}

/** All icon filenames from public/SafetyIcons/. */
const FILENAMES = [
  'Beispiel-Rettungsweg-Notausgang-E002-Zusatzzeichen.png',
  'D-E019_Notausstieg.png',
  'D-P006-Zutritt-fuer-Unbefugte-verboten.png',
  'D-P022-Besteigen-fuer-Unbefugte-verboten.png',
  'D-W021-Warnung-vor-explosionsfaehiger-Atmosphaere.png',
  'E001-Rettungsweg-Notausgang-links.png',
  'E002-Rettungsweg-Notausgang-rechts.png',
  'E003-Erste-Hilfe.png',
  'E004-Notruftelefon.png',
  'E007-Sammelstelle.png',
  'E009-Arzt.png',
  'E010-Automatisierter-Externer-Defibrillator-AED.png',
  'E011-Augenspueleinrichtung.png',
  'E012-Notdusche.png',
  'E013-Krankentrage.png',
  'E016-Notausstieg-mit-Fluchtleiter.png',
  'E017-Rettungsausstieg.png',
  'F001-Feuerloescher.png',
  'F002-Loeschschlauch.png',
  'F003-Feuerleiter.png',
  'F004-Mittel-und-Geraete-zur-Brandbekaempfung.png',
  'F005-Brandmelder.png',
  'F006-Brandmeldetelefon.png',
  'GHS_01_gr.png',
  'GHS_02_gr.png',
  'GHS_03_gr.png',
  'GHS_04_gr.png',
  'GHS_05_gr.png',
  'GHS_06_gr.png',
  'GHS_07_gr.png',
  'GHS_08_gr.png',
  'GHS_09_gr.png',
  'M001_Allgemeines-Gebotszeichen.png',
  'M003_Gehoerschutz-benutzen.png',
  'M004_Augenschutz-benutzen.png',
  'M008_Fussschutz-benutzen.png',
  'M009_Handschutz_benutzen.png',
  'M010_Schutzkleidung-benutzen.png',
  'M011-Haende-waschen.png',
  'M012_Handlauf-benutzen.png',
  'M013_Gesichtsschutz-benutzen.png',
  'M014_Kopfschutz-benutzen.png',
  'M015_Warnweste-benutzen.png',
  'M017_Atemschutz-benutzen.png',
  'M018-Auffanggurt-benutzen.png',
  'M020-Rueckhaltesystem-benutzen.png',
  'M021-Vor-Wartung-oder-Reparatur-freischalten.png',
  'M022-Hautschutzmittel-benutzen.png',
  'M023-Uebergang-benutzen.png',
  'M024-Fussgaengerweg-benutzen.png',
  'M026-Schutzschuerze-benutzen.png',
  'P001-Allgemeines-Verbotszeichen.png',
  'P002-Rauchen-verboten.png',
  'P003-Keine-offene-Flamme.png',
  'P004-Fuer-Fussgaenger-verboten.png',
  'P005-Kein-Trinkwasser.png',
  'P006-Fuer-Flurfoerderzeuge-verboten.png',
  'P007-Kein-Zutritt-fuer-Personen-mit-Herzschrittmachern.png',
  'P010-Beruehren-verboten.png',
  'P011-Mit-Wasser-loeschen-verboten.png',
  'P012-keine-schwere-Last.png',
  'P013-Eingeschaltete-Mobiltelefone-verboten.png',
  'P014-Kein-Zutritt-fuer-Personen-mit-Implantaten.png',
  'P015_Hineinfassen_verboten.png',
  'P016-Mit-Wasser-spritzen-verboten.png',
  'P020-Aufzug-im-Brandfall-nicht-benutzen.png',
  'P021-Mitfuehren-von-Hunden-verboten.png',
  'P022-Essen-und-Trinken-verboten.png',
  'P023-Abstellen-oder-Lagern-verboten.png',
  'P024-Betreten-der-Flaeche-verboten.png',
  'P027-Personenbefoerderung-verboten.png',
  'P028-Benutzen-von-Handschuhen-verboten.png',
  'P031-Schalten-verboten.png',
  'P042-Fuer-schwangere-Frauen-verboten.png',
  'PI001_Maximale_Belastung.png',
  'PI002_Nur_eine_Person.png',
  'PI003_Nicht_hinauslehnen.png',
  'PI004_Ebener_und_tragfaehiger_Untergrund.png',
  'PI005_Witterungsbedingungen.png',
  'PI006_Anlegewinkel_beachten.png',
  'PI007_Nur_an_sichere_Flaechen_anlegen.png',
  'PI008_Die_obersten_3_Sprossen_nicht_besteigen.png',
  'PI009_Die_obersten_4_Sprossen_nicht_besteigen.png',
  'PI010_Mindestens_1m_UEberstand.png',
  'PI011_Stahlspitzen_auf_nachgiebigem_Untergrund.png',
  'PI012_Nicht_uebertreten.png',
  'PI013_Gespannte_Spreizvorrichtung.png',
  'PI014_Nicht_als_Anlegeleiter_nutzen.png',
  'PI015_Nicht_uebersteigen.png',
  'PI016_Spreizsicherung_einlegen.png',
  'Reichtungspfeil_rechts.png',
  'Reichtungspfeil_Rettung_rechts.png',
  'Rettungsweg-Notausgang-E002-Zusatzzeichen.png',
  'Richtungspfeil_rechts_unten.png',
  'Richtungspfeil_Rettung_rechts_unten.png',
  'W001-Allgemeines-Warnzeichen.png',
  'W002 Warnung vor explosionsgefährlichen Stoffen.png',
  'W003_Warnung_vor_radioaktiven_Stoffen_oder_ionisierender_Strahlung.png',
  'W004-Warnung-vor-Laserstrahl.png',
  'W005 Warnung vor nicht ionisierender Strahlung.png',
  'W006 Warnung vor magnetischem Feld.png',
  'W007 Warnung vor Hindernissen am Boden.png',
  'W008 Warnung vor Absturzgefahr.png',
  'W009 Warnung vor Biogefährdung.png',
  'W010-Warnung-vor-niedriger-Temperatur-Frost.png',
  'W011-Warnung-vor-Rutschgefahr.png',
  'W012-Warnung-vor-elektrischer-Spannung.png',
  'W014-Warnung-vor-Flurfoerderzeugen.png',
  'W015-Warnung-vor-schwebender-Last.png',
  'W016-Warnung-vor-giftigen-Stoffen.png',
  'W017-Warnung-vor-heisser-Oberflaeche.png',
  'W018-Warnung-vor-automatischem-Anlauf.png',
  'W019-Warnung-vor-Quetschgefahr.png',
  'W021-Warnung-vor-feuergefaehrlichen.png',
  'W023-Warnung-vor-aetzenden-Stoffen.png',
  'W024-Warnung-vor-Handverletzungen.png',
  'W025-Warnung-vor-gegenlaeufigen-Rollen.png',
  'W026-Warnung-vor-Gefahren-durch-das-Aufladen-von-Batterien.png',
  'W027-Warnung-vor-optischer-Strahlung.png',
  'W028-Warnung-vor-brandfoerdernden-Stoffen.png',
  'W029-Warnung-vor-Gasflaschen.png',
  'W041-Warnung-vor-Erstickungsgefahr.png',
  'WSE001-Oeffentliche-Rettungsausruestung.png',
  'WSM001-Rettungsweste-benutzen.png',
  'WSP001-Laufen-verboten.png',
] as const;

/** Complete manifest: filename + derived category for every icon. */
export const SAFETY_ICON_MANIFEST: SafetyIconEntry[] = FILENAMES.map((filename) => ({
  filename,
  category: getCategoryFromFilename(filename),
}));

/** Quick lookup: filename → manifest entry. */
export const SAFETY_ICON_BY_FILENAME = new Map(
  SAFETY_ICON_MANIFEST.map((entry) => [entry.filename, entry])
);
