import { useTranslation } from 'react-i18next';
import { publicAsset } from '@/lib/media';
import { useMediaResolver } from '@/lib/MediaResolverContext';
import { PrintPageFooter } from './PrintPageFooter';

interface PrintCoverPageProps {
  instructionName: string;
  instructionDescription: string | null;
  coverImageAreaId: string | null;
  articleNumber: string | null;
  estimatedDuration: number | null;
  onImageLoad?: () => void;
  onImageError?: () => void;
}

/**
 * Cover page for the print document.
 * Full page with instruction name, cover image, metadata, and Montavis logo.
 */
export function PrintCoverPage({
  instructionName,
  instructionDescription,
  coverImageAreaId,
  articleNumber,
  estimatedDuration,
  onImageLoad,
  onImageError,
}: PrintCoverPageProps) {
  const { t } = useTranslation();
  const resolver = useMediaResolver();

  const resolved = coverImageAreaId ? resolver.resolveImage(coverImageAreaId) : null;
  if (resolved && resolved.kind !== 'url') {
    console.warn('[PrintCoverPage] Unexpected resolver kind for cover image:', resolved.kind);
  }
  const coverImageUrl = resolved?.kind === 'url' ? resolved.url : null;

  const logoUrl = publicAsset('logo.svg');

  return (
    <div className="print-page-break print-page" data-testid="print-cover-page">
      {/* Title */}
      <div className="print-accent-border-bottom" style={{ marginBottom: '1rem' }}>
        <h1>{instructionName}</h1>
        {instructionDescription && (
          <p style={{ marginTop: '0.375rem', color: 'var(--print-text-muted)', fontSize: '0.75rem' }}>
            {instructionDescription}
          </p>
        )}
      </div>

      {/* Cover image */}
      {coverImageUrl ? (
        <div className="print-image-container print-cover-image" style={{ marginBottom: '1rem' }}>
          <img
            src={coverImageUrl}
            alt={instructionName}
            onLoad={onImageLoad}
            onError={onImageError}
            loading="eager"
          />
        </div>
      ) : (
        <div className="print-no-image" style={{ marginBottom: '1rem', minHeight: '12.5rem' }}>
          {t('printView.noImage', 'No image')}
        </div>
      )}

      {/* Metadata row */}
      <dl className="print-metadata-row" style={{ marginBottom: '1rem' }}>
        {articleNumber && (
          <div>
            <dt>{t('printView.articleNumber', 'Article Number')}</dt>
            <dd>{articleNumber}</dd>
          </div>
        )}
        {estimatedDuration !== null && estimatedDuration > 0 && (
          <div>
            <dt>{t('printView.estimatedDuration', 'Estimated Duration')}</dt>
            <dd>{estimatedDuration} {t('printView.durationUnit', 'min')}</dd>
          </div>
        )}
      </dl>

      {/* Spacer */}
      <div className="print-page-spacer" />

      {/* Logo + generated by */}
      <div className="print-cover-footer">
        <img
          src={logoUrl}
          alt="Montavis"
          className="print-logo"
        />
        <span style={{ fontSize: '0.5625rem', color: 'var(--print-text-muted)' }}>
          {t('printView.generatedBy', 'Generated by Montavis')}
        </span>
      </div>

      <PrintPageFooter instructionName={instructionName} pageNumber={1} />
    </div>
  );
}
