import { useTranslation } from 'react-i18next';
import { buildMediaUrl, MediaPaths, publicAsset } from '@/lib/media';
import { PrintPageFooter } from './PrintPageFooter';

interface PrintCoverPageProps {
  instructionName: string;
  instructionDescription: string | null;
  coverImageAreaId: string | null;
  articleNumber: string | null;
  estimatedDuration: number | null;
  folderName: string;
  onImageLoad?: () => void;
  onImageError?: () => void;
}

/**
 * Cover page for the print document.
 * Full page with instruction name, cover image, metadata, and Montavis logo.
 */
export function PrintCoverPage({
  instructionName,
  instructionDescription,
  coverImageAreaId,
  articleNumber,
  estimatedDuration,
  folderName,
  onImageLoad,
  onImageError,
}: PrintCoverPageProps) {
  const { t } = useTranslation();

  const coverImageUrl = coverImageAreaId
    ? buildMediaUrl(folderName, MediaPaths.frame(coverImageAreaId))
    : null;

  const logoUrl = publicAsset('logo.svg');

  return (
    <div className="print-page-break" data-testid="print-cover-page" style={{ display: 'flex', flexDirection: 'column', minHeight: '95vh' }}>
      {/* Title */}
      <div className="print-accent-border-bottom" style={{ marginBottom: '1rem' }}>
        <h1>{instructionName}</h1>
        {instructionDescription && (
          <p style={{ marginTop: '0.375rem', color: 'var(--print-text-muted)', fontSize: '0.75rem' }}>
            {instructionDescription}
          </p>
        )}
      </div>

      {/* Cover image */}
      {coverImageUrl ? (
        <div className="print-image-container print-cover-image" style={{ marginBottom: '1rem' }}>
          <img
            src={coverImageUrl}
            alt={instructionName}
            onLoad={onImageLoad}
            onError={onImageError}
            loading="eager"
          />
        </div>
      ) : (
        <div className="print-no-image" style={{ marginBottom: '1rem', minHeight: '12.5rem' }}>
          {t('printView.noImage', 'No image')}
        </div>
      )}

      {/* Metadata row */}
      <dl className="print-metadata-row" style={{ marginBottom: '1rem' }}>
        {articleNumber && (
          <div>
            <dt>{t('printView.articleNumber', 'Article Number')}</dt>
            <dd>{articleNumber}</dd>
          </div>
        )}
        {estimatedDuration !== null && estimatedDuration > 0 && (
          <div>
            <dt>{t('printView.estimatedDuration', 'Estimated Duration')}</dt>
            <dd>{estimatedDuration} min</dd>
          </div>
        )}
      </dl>

      {/* Spacer */}
      <div style={{ flex: 1 }} />

      {/* Logo + generated by */}
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', borderTop: '0.0625rem solid var(--print-border)', paddingTop: '0.5rem' }}>
        <img
          src={logoUrl}
          alt="Montavis"
          className="print-logo"
        />
        <span style={{ fontSize: '0.5625rem', color: 'var(--print-text-muted)' }}>
          {t('printView.generatedBy', 'Generated by Montavis')}
        </span>
      </div>

      <PrintPageFooter instructionName={instructionName} pageNumber={1} />
    </div>
  );
}
